version: 0.2

env:
  variables:
    ENVIRONMENT_NAME: "$1"
    VPC_ID: "$2"
    SUBNET_ID: "$3"

phases:
  build:
    commands:
      - printenv
      - echo " This is Simple Buildspec file to execute a shell script and create a CF stack"
      - bash Practice-Demo-on-15-12-19/Test-Build-Project-Repo/scripts/ec2_create.sh $ENVIRONMENT_NAME $VPC_ID $SUBNET_ID   
